name: 'setup-workflow-action'
description: 'javascript action for setting up github actions workflow.'
author: 'Masaya Kataoka'
branding:
  icon: "arrow-right"
  color: "blue"
inputs:
  template:
    required: true
    description: 'path to the template workflow'
  parameters:
    required: false
    description: 'parameters described in workflow {{ parameter.key }} in json format {key, value}'
    default: '{}'
runs:
  using: 'node12'
  main: 'dist/setup_workflow_action.js'